/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author Swamy Naidu
 */
public class rental_admin_reg extends javax.swing.JFrame {

    /**
     * Creates new form rental
     */
    public rental_admin_reg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        admin_user_name = new javax.swing.JTextField();
        admin_pwd = new javax.swing.JTextField();
        admin_confirm_pwd = new javax.swing.JTextField();
        admin_security_qstn = new javax.swing.JTextField();
        admin_security_answer = new javax.swing.JTextField();
        admin_registr_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));
        setForeground(new java.awt.Color(0, 153, 255));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        admin_user_name.setText("User Name");
        admin_user_name.setToolTipText("");
        admin_user_name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        admin_user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_user_nameActionPerformed(evt);
            }
        });

        admin_pwd.setText("Password");
        admin_pwd.setToolTipText("");
        admin_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_pwdActionPerformed(evt);
            }
        });

        admin_confirm_pwd.setText("Confirm Password");
        admin_confirm_pwd.setToolTipText("");
        admin_confirm_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_confirm_pwdActionPerformed(evt);
            }
        });

        admin_security_qstn.setText("Security Question");
        admin_security_qstn.setToolTipText("");
        admin_security_qstn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_security_qstnActionPerformed(evt);
            }
        });

        admin_security_answer.setText("Security Answer");
        admin_security_answer.setToolTipText("");
        admin_security_answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_security_answerActionPerformed(evt);
            }
        });

        admin_registr_btn.setText("Register");
        admin_registr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_registr_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("              Admin Registration ");

        jLabel2.setText("Company Logo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(admin_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(admin_pwd, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(admin_confirm_pwd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                            .addComponent(admin_security_answer)
                            .addComponent(admin_security_qstn, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(admin_registr_btn)))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(admin_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(admin_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(admin_confirm_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(admin_security_qstn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(admin_security_answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(admin_registr_btn)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admin_user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_user_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_user_nameActionPerformed

    private void admin_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_pwdActionPerformed

    private void admin_confirm_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_confirm_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_confirm_pwdActionPerformed

    private void admin_security_answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_security_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_security_answerActionPerformed

    private void admin_security_qstnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_security_qstnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_security_qstnActionPerformed

    private void admin_registr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_registr_btnActionPerformed
        // TODO add your handling code here:
        String admin_reg_user_name=admin_user_name.getText();
        String admin_reg_pwd=admin_pwd.getText();
        String admin_reg_confirm_pwd=admin_confirm_pwd.getText();
        String admin_reg_security_qstn=admin_security_qstn.getText();
        String admin_reg_security_answer=admin_security_answer.getText();
        Boolean valid=true;
        //do validation
        validations validation_object=new validations();
        valid=validation_object.admin_reg_validations(admin_reg_user_name,admin_reg_pwd);
        
        
        ArrayList list=new ArrayList();//Creating arraylist  
        list.add(admin_reg_user_name);//Adding object in arraylist  
        list.add(admin_reg_pwd);  
        list.add(admin_reg_confirm_pwd);  
        list.add(admin_reg_security_qstn);
        list.add(admin_reg_security_answer);
        //Traversing list through Iterator  
        Iterator itr=list.iterator();  
        while(itr.hasNext()){  
         System.out.println(itr.next());  
        } 
        new login().setVisible(true);
        
        
    }//GEN-LAST:event_admin_registr_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rental_admin_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rental_admin_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rental_admin_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rental_admin_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rental_admin_reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField admin_confirm_pwd;
    private javax.swing.JTextField admin_pwd;
    private javax.swing.JButton admin_registr_btn;
    private javax.swing.JTextField admin_security_answer;
    private javax.swing.JTextField admin_security_qstn;
    private javax.swing.JTextField admin_user_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
